import { LocalizedText } from "./localized";
import { Offer } from "./types";

export const offersByPersona: Record<string, { collectionName: LocalizedText; offers: Offer[] }> = {
  anna: {
    collectionName: {
      en: "SecurFinancial Mortgage & Banking Offers",
      pl: "Oferty hipoteczne i bankowe SecurFinancial",
      de: "SecurFinancial Hypotheken- und Bankangebote",
      it: "Offerte mutui e bancarie SecurFinancial",
    },
    offers: [
      {
        id: "lock_mortgage_rate",
        name: {
          en: "Lock In Your Mortgage Rate",
          pl: "Zablokuj swoje oprocentowanie kredytu hipotecznego",
          de: "Sichern Sie sich Ihren Hypothekenzins",
          it: "Blocca il tuo tasso di mutuo",
        },
        description: {
          en: "Secure today's rate on your pre-approved mortgage before it changes.",
          pl: "Zabezpiecz dzisiejsze oprocentowanie wstępnie zatwierdzonego kredytu hipotecznego, zanim się zmieni.",
          de: "Sichern Sie sich den heutigen Zinssatz für Ihre vorab genehmigte Hypothek, bevor er sich ändert.",
          it: "Blocca subito il tasso sul tuo mutuo pre-approvato prima che cambi.",
        },
        cta: { en: "Lock in my rate", pl: "Zablokuj moje oprocentowanie", de: "Zinssatz sichern", it: "Blocca il mio tasso" },
        mobileName: {
          en: "Lock In Your Rate",
          pl: "Zablokuj oprocentowanie",
          de: "Zinssatz sichern",
          it: "Blocca il tasso",
        },
        mobileDescription: {
          en: "Secure today's rate before it changes.",
          pl: "Zabezpiecz dzisiejsze oprocentowanie, zanim się zmieni.",
          de: "Sichern Sie sich den heutigen Zinssatz, bevor er sich ändert.",
          it: "Blocca subito il tasso prima che cambi.",
        },
        mobileCta: { en: "Lock in", pl: "Zablokuj", de: "Sichern", it: "Blocca" },
        requiredSignals: ["mortgage_calc"],
        priority: 75,
        affinityTags: ["mortgage_calc"],
        imageUrl: "/banners/mortgage-loans.png",
        mobileImageUrl: "/banners/mortgage-loans-mobile.png",
      },
      {
        id: "finish_application",
        name: {
          en: "Finish Your Application — Fee Waived",
          pl: "Dokończ wniosek — bez opłaty",
          de: "Antrag abschließen — Gebühr erlassen",
          it: "Completa la domanda — commissione azzerata",
        },
        description: {
          en: "Complete your mortgage application now and we'll waive the processing fee.",
          pl: "Dokończ teraz swój wniosek o kredyt hipoteczny, a zniesiemy opłatę za jego przetworzenie.",
          de: "Schließen Sie jetzt Ihren Hypothekenantrag ab, und wir erlassen Ihnen die Bearbeitungsgebühr.",
          it: "Completa ora la tua domanda di mutuo e ti azzeriamo la commissione di istruttoria.",
        },
        cta: { en: "Finish my application", pl: "Dokończ mój wniosek", de: "Antrag abschließen", it: "Completa la domanda" },
        mobileName: {
          en: "Finish & Skip the Fee",
          pl: "Dokończ i pomiń opłatę",
          de: "Abschließen & Gebühr sparen",
          it: "Completa e risparmia",
        },
        mobileDescription: {
          en: "Finish now, fee waived.",
          pl: "Dokończ teraz, bez opłaty.",
          de: "Jetzt abschließen, Gebühr erlassen.",
          it: "Completa ora, senza commissione.",
        },
        mobileCta: { en: "Finish now", pl: "Dokończ teraz", de: "Jetzt abschließen", it: "Completa ora" },
        requiredSignals: ["app_abandoned"],
        priority: 90,
        affinityTags: ["app_abandoned"],
        imageUrl: "/banners/mortgage-loans.png",
        mobileImageUrl: "/banners/mortgage-loans-mobile.png",
      },
      {
        id: "loyalty_reward",
        name: {
          en: "A Thank-You, On Us: 6 Months Fee-Free",
          pl: "Podziękowanie od nas: 6 miesięcy bez opłat",
          de: "Ein Dankeschön von uns: 6 Monate gebührenfrei",
          it: "Un ringraziamento da noi: 6 mesi senza commissioni",
        },
        description: {
          en: "After your recent call, we've waived your account fees for the next 6 months — already applied.",
          pl: "Po Twoim niedawnym telefonie zniosliśmy opłaty za konto na kolejne 6 miesięcy — zmiana już obowiązuje.",
          de: "Nach Ihrem kürzlichen Anruf haben wir Ihre Kontogebühren für die nächsten 6 Monate erlassen — bereits angewendet.",
          it: "Dopo la tua recente chiamata, abbiamo azzerato le commissioni del conto per i prossimi 6 mesi — già applicato.",
        },
        cta: { en: "Claim my reward", pl: "Odbierz nagrodę", de: "Prämie einlösen", it: "Ritira il premio" },
        mobileName: { en: "6 Months, Fee-Free", pl: "6 miesięcy bez opłat", de: "6 Monate gebührenfrei", it: "6 mesi senza commissioni" },
        mobileDescription: {
          en: "Fees waived for 6 months. Already applied.",
          pl: "Opłaty zniesione na 6 miesięcy. Zmiana już obowiązuje.",
          de: "Gebühren für 6 Monate erlassen. Bereits angewendet.",
          it: "Commissioni azzerate per 6 mesi. Già applicato.",
        },
        mobileCta: { en: "Claim reward", pl: "Odbierz nagrodę", de: "Prämie einlösen", it: "Ritira il premio" },
        requiredSignals: ["sentiment_dissatisfied", "customer_existing"],
        priority: 95,
        affinityTags: ["sentiment_dissatisfied"],
        imageUrl: "/banners/private-banking.png",
        mobileImageUrl: "/banners/private-banking-mobile.png",
      },
      {
        id: "family_protection",
        name: {
          en: "Protect What Matters: Family Coverage Review",
          pl: "Chroń to, co ważne: przegląd ochrony rodzinnej",
          de: "Schützen Sie, was zählt: Familienschutz-Check",
          it: "Proteggi ciò che conta: revisione copertura familiare",
        },
        description: {
          en: "Now that your family is growing, let's make sure your coverage keeps up.",
          pl: "Twoja rodzina się powiększa — upewnijmy się, że Twoja ochrona nadąża za zmianami.",
          de: "Da Ihre Familie wächst, sollten wir sicherstellen, dass Ihr Versicherungsschutz mithält.",
          it: "Ora che la tua famiglia cresce, assicuriamoci che la tua copertura sia adeguata.",
        },
        cta: { en: "Review my coverage", pl: "Sprawdź moją ochronę", de: "Schutz überprüfen", it: "Rivedi la mia copertura" },
        mobileName: { en: "Protect Your Family", pl: "Chroń swoją rodzinę", de: "Familie schützen", it: "Proteggi la tua famiglia" },
        mobileDescription: {
          en: "Make sure your coverage keeps up.",
          pl: "Upewnij się, że Twoja ochrona nadąża za zmianami.",
          de: "Stellen Sie sicher, dass Ihr Schutz mithält.",
          it: "Assicurati che la tua copertura sia adeguata.",
        },
        mobileCta: { en: "Review coverage", pl: "Sprawdź ochronę", de: "Schutz prüfen", it: "Rivedi copertura" },
        requiredSignals: ["has_family"],
        priority: 80,
        affinityTags: ["has_family", "profession_stay_home"],
        imageUrl: "/banners/family-protection.png",
        mobileImageUrl: "/banners/family-protection-mobile.png",
      },
      {
        id: "business_banking",
        name: {
          en: "Business Banking for the Self-Employed",
          pl: "Bankowość biznesowa dla samozatrudnionych",
          de: "Geschäftskonten für Selbstständige",
          it: "Conto business per i lavoratori autonomi",
        },
        description: {
          en: "Flexible business banking built for variable, self-employed income.",
          pl: "Elastyczna bankowość biznesowa stworzona dla zmiennych dochodów z samozatrudnienia.",
          de: "Flexible Geschäftskonten, konzipiert für variable Einkünfte von Selbstständigen.",
          it: "Servizi bancari business flessibili, pensati per redditi variabili da lavoro autonomo.",
        },
        cta: { en: "Open a business account", pl: "Otwórz konto firmowe", de: "Geschäftskonto eröffnen", it: "Apri un conto business" },
        mobileName: {
          en: "Banking for the Self-Employed",
          pl: "Bankowość dla samozatrudnionych",
          de: "Banking für Selbstständige",
          it: "Banking per autonomi",
        },
        mobileDescription: {
          en: "Built for variable, self-employed income.",
          pl: "Stworzone dla zmiennych dochodów z samozatrudnienia.",
          de: "Konzipiert für variable Einkünfte von Selbstständigen.",
          it: "Pensato per redditi variabili da lavoro autonomo.",
        },
        mobileCta: { en: "Open account", pl: "Otwórz konto", de: "Konto eröffnen", it: "Apri conto" },
        requiredSignals: ["profession_hairdresser"],
        priority: 62,
        affinityTags: ["profession_hairdresser"],
        imageUrl: "/banners/self-employed-banking.png",
        mobileImageUrl: "/banners/self-employed-banking-mobile.png",
      },
      {
        id: "premium_digital",
        name: {
          en: "Open a Premium Digital Account in Minutes",
          pl: "Otwórz konto Premium Digital w kilka minut",
          de: "Premium-Digitalkonto in wenigen Minuten eröffnen",
          it: "Apri un conto digitale Premium in pochi minuti",
        },
        description: {
          en: "Built for busy professionals — everything set up from your phone, no branch visit needed.",
          pl: "Stworzone dla zapracowanych profesjonalistów — wszystko ustawisz z telefonu, bez wizyty w oddziale.",
          de: "Für vielbeschäftigte Berufstätige — alles vom Smartphone aus einrichten, ohne Filialbesuch.",
          it: "Pensato per professionisti impegnati — tutto configurabile dal telefono, senza andare in filiale.",
        },
        cta: { en: "Open my account", pl: "Otwórz moje konto", de: "Konto eröffnen", it: "Apri il mio conto" },
        mobileName: {
          en: "Open an Account in Minutes",
          pl: "Otwórz konto w kilka minut",
          de: "Konto in wenigen Minuten eröffnen",
          it: "Apri un conto in pochi minuti",
        },
        mobileDescription: {
          en: "Set up from your phone. No branch visit.",
          pl: "Ustaw z telefonu. Bez wizyty w oddziale.",
          de: "Einrichtung per Smartphone. Kein Filialbesuch.",
          it: "Configura dal telefono. Niente filiale.",
        },
        mobileCta: { en: "Open account", pl: "Otwórz konto", de: "Konto eröffnen", it: "Apri conto" },
        requiredSignals: ["profession_pm", "customer_prospect"],
        priority: 62,
        affinityTags: ["profession_pm"],
        imageUrl: "/banners/premium-digital.png",
        mobileImageUrl: "/banners/premium-digital-mobile.png",
      },
      {
        id: "later_life_planning",
        name: { en: "Plan for What's Next", pl: "Zaplanuj to, co przed Tobą", de: "Planen Sie, was als Nächstes kommt", it: "Pianifica il prossimo passo" },
        description: {
          en: "Later-life banking and estate planning, made simple.",
          pl: "Bankowość na później i planowanie spadkowe — w prostej formie.",
          de: "Banking im Ruhestand und Nachlassplanung, einfach gemacht.",
          it: "Servizi bancari per la terza età e pianificazione patrimoniale, semplificati.",
        },
        cta: { en: "Start planning", pl: "Zacznij planować", de: "Planung starten", it: "Inizia a pianificare" },
        mobileDescription: {
          en: "Estate planning, made simple.",
          pl: "Planowanie spadkowe w prostej formie.",
          de: "Nachlassplanung, einfach gemacht.",
          it: "Pianificazione patrimoniale, semplificata.",
        },
        requiredSignals: ["age_50s"],
        priority: 65,
        affinityTags: ["age_50s"],
        imageUrl: "/banners/retirement.png",
        mobileImageUrl: "/banners/retirement-mobile.png",
      },
      {
        id: "starter_banking",
        name: { en: "Starter Banking Bundle", pl: "Pakiet bankowy dla początkujących", de: "Starter-Bankpaket", it: "Pacchetto bancario iniziale" },
        description: {
          en: "Everything you need to build good financial habits early.",
          pl: "Wszystko, czego potrzebujesz, by wcześnie wyrobić sobie dobre nawyki finansowe.",
          de: "Alles, was Sie brauchen, um früh gute Finanzgewohnheiten aufzubauen.",
          it: "Tutto ciò che serve per costruire presto buone abitudini finanziarie.",
        },
        cta: { en: "Get started", pl: "Zacznij teraz", de: "Jetzt starten", it: "Inizia ora" },
        mobileDescription: {
          en: "Build good habits early.",
          pl: "Wyrób sobie dobre nawyki wcześnie.",
          de: "Bauen Sie früh gute Gewohnheiten auf.",
          it: "Costruisci presto buone abitudini.",
        },
        requiredSignals: ["age_30s"],
        priority: 60,
        affinityTags: ["age_30s"],
        imageUrl: "/banners/savings-accounts.png",
        mobileImageUrl: "/banners/savings-accounts-mobile.png",
      },
      {
        id: "welcome_savings",
        name: {
          en: "Welcome Bonus: Open a Savings Account",
          pl: "Bonus powitalny: otwórz konto oszczędnościowe",
          de: "Willkommensbonus: Sparkonto eröffnen",
          it: "Bonus di benvenuto: apri un conto di risparmio",
        },
        description: {
          en: "A general-interest pick for customers still exploring their options.",
          pl: "Propozycja ogólna dla klientów, którzy wciąż rozważają swoje opcje.",
          de: "Ein allgemeiner Vorschlag für Kunden, die noch ihre Möglichkeiten prüfen.",
          it: "Una proposta generale per i clienti che stanno ancora valutando le opzioni.",
        },
        cta: { en: "Open a savings account", pl: "Otwórz konto oszczędnościowe", de: "Sparkonto eröffnen", it: "Apri un conto di risparmio" },
        mobileName: {
          en: "Welcome Bonus: Open Savings",
          pl: "Bonus powitalny: konto oszczędnościowe",
          de: "Willkommensbonus: Sparkonto",
          it: "Bonus di benvenuto: risparmio",
        },
        mobileDescription: {
          en: "Still exploring your options? Start here.",
          pl: "Wciąż rozważasz opcje? Zacznij tutaj.",
          de: "Noch unentschlossen? Hier starten.",
          it: "Stai ancora valutando? Inizia qui.",
        },
        mobileCta: { en: "Open savings", pl: "Otwórz konto", de: "Sparkonto eröffnen", it: "Apri risparmio" },
        requiredSignals: [],
        priority: 40,
        affinityTags: [],
        imageUrl: "/banners/savings-accounts.png",
        mobileImageUrl: "/banners/savings-accounts-mobile.png",
      },
    ],
  },
  lukas: {
    collectionName: {
      en: "SecurFinancial Wealth & Retirement Offers",
      pl: "Oferty majątkowe i emerytalne SecurFinancial",
      de: "SecurFinancial Vermögens- und Altersvorsorgeangebote",
      it: "Offerte patrimoniali e pensionistiche SecurFinancial",
    },
    offers: [
      {
        id: "boost_retirement",
        name: {
          en: "Boost Your Retirement Contributions",
          pl: "Zwiększ swoje składki emerytalne",
          de: "Erhöhen Sie Ihre Altersvorsorgebeiträge",
          it: "Aumenta i tuoi contributi pensionistici",
        },
        description: {
          en: "Increase your contribution rate and see the long-term projected impact.",
          pl: "Zwiększ stawkę składki i zobacz długoterminowy prognozowany efekt.",
          de: "Erhöhen Sie Ihre Beitragsrate und sehen Sie die langfristige prognostizierte Wirkung.",
          it: "Aumenta il tasso di contribuzione e scopri l'impatto proiettato nel lungo periodo.",
        },
        cta: { en: "Boost my contributions", pl: "Zwiększ moje składki", de: "Beiträge erhöhen", it: "Aumenta i miei contributi" },
        mobileName: {
          en: "Boost Your Retirement",
          pl: "Zwiększ swoją emeryturę",
          de: "Altersvorsorge steigern",
          it: "Potenzia la tua pensione",
        },
        mobileDescription: {
          en: "See the long-term impact.",
          pl: "Zobacz długoterminowy efekt.",
          de: "Sehen Sie die langfristige Wirkung.",
          it: "Scopri l'impatto nel lungo periodo.",
        },
        mobileCta: { en: "Boost now", pl: "Zwiększ teraz", de: "Jetzt erhöhen", it: "Aumenta ora" },
        requiredSignals: ["retirement_interest"],
        priority: 70,
        affinityTags: ["retirement_interest", "age_50s", "profession_pm"],
        imageUrl: "/banners/retirement.png",
        mobileImageUrl: "/banners/retirement-mobile.png",
      },
      {
        id: "finish_investment_setup",
        name: {
          en: "Complete Your Investment Setup",
          pl: "Dokończ konfigurację inwestycji",
          de: "Schließen Sie Ihre Investment-Einrichtung ab",
          it: "Completa la configurazione dell'investimento",
        },
        description: {
          en: "You're almost there — finish setting up your investment account today.",
          pl: "Jesteś już prawie na miejscu — dokończ dziś konfigurację rachunku inwestycyjnego.",
          de: "Sie sind fast am Ziel — schließen Sie heute die Einrichtung Ihres Investmentkontos ab.",
          it: "Ci sei quasi — completa oggi la configurazione del tuo conto d'investimento.",
        },
        cta: { en: "Finish my setup", pl: "Dokończ konfigurację", de: "Einrichtung abschließen", it: "Completa la configurazione" },
        mobileName: { en: "Finish Your Setup", pl: "Dokończ konfigurację", de: "Einrichtung abschließen", it: "Completa la configurazione" },
        mobileDescription: {
          en: "Almost there — finish today.",
          pl: "Już prawie gotowe — dokończ dziś.",
          de: "Fast geschafft — heute abschließen.",
          it: "Ci sei quasi — completa oggi.",
        },
        requiredSignals: ["app_abandoned"],
        priority: 88,
        affinityTags: ["app_abandoned"],
        imageUrl: "/banners/investment.png",
        mobileImageUrl: "/banners/investment-mobile.png",
      },
      {
        id: "loyalty_reward",
        name: {
          en: "A Thank-You, On Us: Reduced Advisory Fees",
          pl: "Podziękowanie od nas: obniżone opłaty doradcze",
          de: "Ein Dankeschön von uns: reduzierte Beratungsgebühren",
          it: "Un ringraziamento da noi: commissioni di consulenza ridotte",
        },
        description: {
          en: "After your recent call, we've reduced your advisory fees for the next quarter — already applied.",
          pl: "Po Twoim niedawnym telefonie obniżyliśmy opłaty doradcze na kolejny kwartał — zmiana już obowiązuje.",
          de: "Nach Ihrem kürzlichen Anruf haben wir Ihre Beratungsgebühren für das nächste Quartal reduziert — bereits angewendet.",
          it: "Dopo la tua recente chiamata, abbiamo ridotto le commissioni di consulenza per il prossimo trimestre — già applicato.",
        },
        cta: { en: "Claim my reward", pl: "Odbierz nagrodę", de: "Prämie einlösen", it: "Ritira il premio" },
        mobileName: {
          en: "Reduced Advisory Fees",
          pl: "Obniżone opłaty doradcze",
          de: "Reduzierte Beratungsgebühren",
          it: "Commissioni di consulenza ridotte",
        },
        mobileDescription: {
          en: "Fees reduced this quarter. Already applied.",
          pl: "Opłaty obniżone w tym kwartale. Zmiana już obowiązuje.",
          de: "Gebühren in diesem Quartal reduziert. Bereits angewendet.",
          it: "Commissioni ridotte questo trimestre. Già applicato.",
        },
        mobileCta: { en: "Claim reward", pl: "Odbierz nagrodę", de: "Prämie einlösen", it: "Ritira il premio" },
        requiredSignals: ["sentiment_dissatisfied", "customer_existing"],
        priority: 95,
        affinityTags: ["sentiment_dissatisfied"],
        imageUrl: "/banners/private-banking.png",
        mobileImageUrl: "/banners/private-banking-mobile.png",
      },
      {
        id: "family_protection",
        name: {
          en: "Set Up a Trust for Your Family",
          pl: "Załóż fundusz powierniczy dla rodziny",
          de: "Richten Sie einen Treuhandfonds für Ihre Familie ein",
          it: "Istituisci un trust per la tua famiglia",
        },
        description: {
          en: "Now that your family is growing, plan how your wealth protects them too.",
          pl: "Twoja rodzina się powiększa — zaplanuj, jak Twój majątek będzie ją chronił.",
          de: "Da Ihre Familie wächst, planen Sie, wie Ihr Vermögen sie ebenfalls schützt.",
          it: "Ora che la tua famiglia cresce, pianifica come il tuo patrimonio possa proteggerla.",
        },
        cta: { en: "Start my trust", pl: "Załóż fundusz", de: "Treuhandfonds einrichten", it: "Istituisci il trust" },
        mobileName: { en: "Set Up a Family Trust", pl: "Załóż fundusz rodzinny", de: "Familientreuhand einrichten", it: "Istituisci un trust familiare" },
        mobileDescription: {
          en: "Plan how your wealth protects them.",
          pl: "Zaplanuj, jak Twój majątek będzie ich chronił.",
          de: "Planen Sie, wie Ihr Vermögen sie schützt.",
          it: "Pianifica come il tuo patrimonio li protegge.",
        },
        mobileCta: { en: "Start trust", pl: "Załóż fundusz", de: "Fonds einrichten", it: "Istituisci trust" },
        requiredSignals: ["has_family"],
        priority: 80,
        affinityTags: ["has_family", "profession_stay_home"],
        imageUrl: "/banners/family-protection.png",
        mobileImageUrl: "/banners/family-protection-mobile.png",
      },
      {
        id: "business_banking",
        name: {
          en: "Business Banking for the Self-Employed",
          pl: "Bankowość biznesowa dla samozatrudnionych",
          de: "Geschäftskonten für Selbstständige",
          it: "Conto business per i lavoratori autonomi",
        },
        description: {
          en: "Flexible business banking built for variable, self-employed income.",
          pl: "Elastyczna bankowość biznesowa stworzona dla zmiennych dochodów z samozatrudnienia.",
          de: "Flexible Geschäftskonten, konzipiert für variable Einkünfte von Selbstständigen.",
          it: "Servizi bancari business flessibili, pensati per redditi variabili da lavoro autonomo.",
        },
        cta: { en: "Open a business account", pl: "Otwórz konto firmowe", de: "Geschäftskonto eröffnen", it: "Apri un conto business" },
        mobileName: {
          en: "Banking for the Self-Employed",
          pl: "Bankowość dla samozatrudnionych",
          de: "Banking für Selbstständige",
          it: "Banking per autonomi",
        },
        mobileDescription: {
          en: "Built for variable, self-employed income.",
          pl: "Stworzone dla zmiennych dochodów z samozatrudnienia.",
          de: "Konzipiert für variable Einkünfte von Selbstständigen.",
          it: "Pensato per redditi variabili da lavoro autonomo.",
        },
        mobileCta: { en: "Open account", pl: "Otwórz konto", de: "Konto eröffnen", it: "Apri conto" },
        requiredSignals: ["profession_hairdresser"],
        priority: 62,
        affinityTags: ["profession_hairdresser"],
        imageUrl: "/banners/self-employed-banking.png",
        mobileImageUrl: "/banners/self-employed-banking-mobile.png",
      },
      {
        id: "premium_digital",
        name: {
          en: "Open a Premium Digital Account in Minutes",
          pl: "Otwórz konto Premium Digital w kilka minut",
          de: "Premium-Digitalkonto in wenigen Minuten eröffnen",
          it: "Apri un conto digitale Premium in pochi minuti",
        },
        description: {
          en: "Built for busy professionals — everything set up from your phone, no branch visit needed.",
          pl: "Stworzone dla zapracowanych profesjonalistów — wszystko ustawisz z telefonu, bez wizyty w oddziale.",
          de: "Für vielbeschäftigte Berufstätige — alles vom Smartphone aus einrichten, ohne Filialbesuch.",
          it: "Pensato per professionisti impegnati — tutto configurabile dal telefono, senza andare in filiale.",
        },
        cta: { en: "Open my account", pl: "Otwórz moje konto", de: "Konto eröffnen", it: "Apri il mio conto" },
        mobileName: {
          en: "Open an Account in Minutes",
          pl: "Otwórz konto w kilka minut",
          de: "Konto in wenigen Minuten eröffnen",
          it: "Apri un conto in pochi minuti",
        },
        mobileDescription: {
          en: "Set up from your phone. No branch visit.",
          pl: "Ustaw z telefonu. Bez wizyty w oddziale.",
          de: "Einrichtung per Smartphone. Kein Filialbesuch.",
          it: "Configura dal telefono. Niente filiale.",
        },
        mobileCta: { en: "Open account", pl: "Otwórz konto", de: "Konto eröffnen", it: "Apri conto" },
        requiredSignals: ["profession_pm", "customer_prospect"],
        priority: 62,
        affinityTags: ["profession_pm"],
        imageUrl: "/banners/premium-digital.png",
        mobileImageUrl: "/banners/premium-digital-mobile.png",
      },
      {
        id: "early_investing",
        name: { en: "Start Investing Early", pl: "Zacznij inwestować wcześnie", de: "Früh mit dem Investieren beginnen", it: "Inizia a investire presto" },
        description: {
          en: "Small contributions now add up significantly by retirement.",
          pl: "Niewielkie wpłaty teraz znacząco się sumują do czasu emerytury.",
          de: "Kleine Beiträge summieren sich bis zur Rente erheblich.",
          it: "Piccoli contributi oggi si sommano in modo significativo entro la pensione.",
        },
        cta: { en: "Start investing", pl: "Zacznij inwestować", de: "Investieren beginnen", it: "Inizia a investire" },
        mobileDescription: {
          en: "Small amounts add up by retirement.",
          pl: "Małe kwoty sumują się do czasu emerytury.",
          de: "Kleine Beträge summieren sich bis zur Rente.",
          it: "Piccole somme si sommano entro la pensione.",
        },
        requiredSignals: ["age_30s"],
        priority: 60,
        affinityTags: ["audience_emerging_investors"],
        imageUrl: "/banners/investment.png",
        mobileImageUrl: "/banners/investment-mobile.png",
      },
      {
        id: "savings_calculator",
        name: {
          en: "Explore Our Savings Calculator",
          pl: "Sprawdź nasz kalkulator oszczędności",
          de: "Entdecken Sie unseren Sparrechner",
          it: "Scopri il nostro calcolatore di risparmio",
        },
        description: {
          en: "A general-interest pick for customers still exploring their options.",
          pl: "Propozycja ogólna dla klientów, którzy wciąż rozważają swoje opcje.",
          de: "Ein allgemeiner Vorschlag für Kunden, die noch ihre Möglichkeiten prüfen.",
          it: "Una proposta generale per i clienti che stanno ancora valutando le opzioni.",
        },
        cta: { en: "Try the calculator", pl: "Wypróbuj kalkulator", de: "Rechner ausprobieren", it: "Prova il calcolatore" },
        mobileName: {
          en: "Try Our Savings Calculator",
          pl: "Wypróbuj kalkulator oszczędności",
          de: "Sparrechner ausprobieren",
          it: "Prova il calcolatore di risparmio",
        },
        mobileDescription: {
          en: "Still exploring? Start here.",
          pl: "Wciąż rozważasz opcje? Zacznij tutaj.",
          de: "Noch unentschlossen? Hier starten.",
          it: "Stai ancora valutando? Inizia qui.",
        },
        requiredSignals: [],
        priority: 35,
        affinityTags: [],
        imageUrl: "/banners/savings-accounts.png",
        mobileImageUrl: "/banners/savings-accounts-mobile.png",
      },
    ],
  },
  marcus: {
    collectionName: {
      en: "TrailGear Outdoor Retail Offers",
      pl: "Oferty outdoorowe TrailGear",
      de: "TrailGear Outdoor-Angebote",
      it: "Offerte outdoor TrailGear",
    },
    offers: [
      {
        id: "shoe_flash_sale",
        name: { en: "Running Shoe Flash Sale", pl: "Błyskawiczna wyprzedaż butów do biegania", de: "Blitzverkauf Laufschuhe", it: "Vendita lampo scarpe da running" },
        description: {
          en: "The shoes you've been eyeing, now 15% off for 48 hours.",
          pl: "Buty, na które od dawna patrzysz, teraz 15% taniej przez 48 godzin.",
          de: "Die Schuhe, die Sie im Blick hatten, jetzt 48 Stunden lang 15 % günstiger.",
          it: "Le scarpe che tenevi d'occhio, ora il 15% in meno per 48 ore.",
        },
        cta: { en: "Shop the sale", pl: "Zobacz wyprzedaż", de: "Zum Angebot", it: "Vai alla vendita" },
        mobileDescription: {
          en: "15% off for 48 hours.",
          pl: "15% taniej przez 48 godzin.",
          de: "48 Stunden lang 15 % günstiger.",
          it: "15% in meno per 48 ore.",
        },
        requiredSignals: ["shoes_interest"],
        priority: 65,
        affinityTags: ["shoes_interest", "age_30s"],
      },
      {
        id: "finish_order",
        name: {
          en: "Finish Your Order — Free Shipping",
          pl: "Dokończ zamówienie — darmowa dostawa",
          de: "Bestellung abschließen — kostenloser Versand",
          it: "Completa l'ordine — spedizione gratuita",
        },
        description: {
          en: "Complete your cart today and shipping is on us.",
          pl: "Dokończ dziś swój koszyk, a dostawę bierzemy na siebie.",
          de: "Schließen Sie Ihren Warenkorb heute ab, der Versand geht auf uns.",
          it: "Completa il carrello oggi e la spedizione è offerta da noi.",
        },
        cta: { en: "Finish my order", pl: "Dokończ zamówienie", de: "Bestellung abschließen", it: "Completa l'ordine" },
        mobileName: { en: "Finish Order, Free Shipping", pl: "Dokończ, darmowa dostawa", de: "Abschließen, gratis Versand", it: "Completa, spedizione gratis" },
        mobileDescription: {
          en: "Shipping's on us today.",
          pl: "Dziś dostawa na nas.",
          de: "Heute geht der Versand auf uns.",
          it: "Oggi la spedizione è offerta da noi.",
        },
        requiredSignals: ["cart_abandoned"],
        priority: 85,
        affinityTags: ["cart_abandoned"],
      },
      {
        id: "recovery_discount",
        name: {
          en: "We're Sorry — Here's 20% Off Your Next Order",
          pl: "Przepraszamy — 20% zniżki na kolejne zamówienie",
          de: "Es tut uns leid — 20 % Rabatt auf Ihre nächste Bestellung",
          it: "Ci scusiamo — ecco il 20% di sconto sul prossimo ordine",
        },
        description: {
          en: "We want to make up for what went wrong on your last order.",
          pl: "Chcemy zrekompensować to, co poszło nie tak przy Twoim ostatnim zamówieniu.",
          de: "Wir möchten wiedergutmachen, was bei Ihrer letzten Bestellung schiefgelaufen ist.",
          it: "Vogliamo rimediare a quanto non ha funzionato nel tuo ultimo ordine.",
        },
        cta: { en: "Claim my discount", pl: "Odbierz zniżkę", de: "Rabatt einlösen", it: "Ritira lo sconto" },
        mobileName: {
          en: "Sorry! 20% Off Next Order",
          pl: "Przepraszamy! 20% zniżki",
          de: "Entschuldigung! 20 % Rabatt",
          it: "Scusa! 20% di sconto",
        },
        mobileDescription: {
          en: "Making up for what went wrong.",
          pl: "Rekompensata za to, co poszło nie tak.",
          de: "Wiedergutmachung für das Missgeschick.",
          it: "Un rimedio per quanto non ha funzionato.",
        },
        mobileCta: { en: "Claim discount", pl: "Odbierz zniżkę", de: "Rabatt einlösen", it: "Ritira sconto" },
        requiredSignals: ["sentiment_dissatisfied"],
        priority: 95,
        affinityTags: ["sentiment_dissatisfied"],
      },
      {
        id: "rain_jackets",
        name: { en: "Weatherproof Jacket Picks", pl: "Wybór kurtek nieprzemakalnych", de: "Auswahl wetterfester Jacken", it: "Selezione giacche impermeabili" },
        description: {
          en: "Curated rain gear picked for your local climate.",
          pl: "Wyselekcjonowany sprzęt przeciwdeszczowy dopasowany do Twojego klimatu.",
          de: "Ausgewählte Regenbekleidung, passend zu Ihrem regionalen Klima.",
          it: "Abbigliamento antipioggia selezionato per il tuo clima locale.",
        },
        cta: { en: "Shop rain gear", pl: "Zobacz sprzęt przeciwdeszczowy", de: "Zur Regenausrüstung", it: "Vai all'abbigliamento antipioggia" },
        mobileDescription: {
          en: "Rain gear for your climate.",
          pl: "Sprzęt przeciwdeszczowy dla Twojego klimatu.",
          de: "Regenausrüstung für Ihr Klima.",
          it: "Abbigliamento antipioggia per il tuo clima.",
        },
        requiredSignals: ["rainy_climate"],
        priority: 55,
        affinityTags: ["rainy_climate", "age_50s"],
      },
      {
        id: "new_arrivals",
        name: { en: "New Arrivals This Week", pl: "Nowości w tym tygodniu", de: "Neuheiten diese Woche", it: "Novità di questa settimana" },
        description: {
          en: "A general-interest pick for browsing customers.",
          pl: "Propozycja ogólna dla klientów przeglądających ofertę.",
          de: "Ein allgemeiner Vorschlag für stöbernde Kunden.",
          it: "Una proposta generale per i clienti che stanno navigando.",
        },
        cta: { en: "See what's new", pl: "Zobacz nowości", de: "Neuheiten ansehen", it: "Scopri le novità" },
        mobileDescription: {
          en: "Fresh picks for browsing.",
          pl: "Świeże propozycje do przeglądania.",
          de: "Frische Vorschläge zum Stöbern.",
          it: "Nuove proposte da scoprire.",
        },
        requiredSignals: [],
        priority: 35,
        affinityTags: [],
      },
    ],
  },
};
