import { Offer } from "./types";

export const offersByPersona: Record<string, { collectionName: string; offers: Offer[] }> = {
  anna: {
    collectionName: "SecurFinancial Mortgage & Banking Offers",
    offers: [
      {
        id: "lock_mortgage_rate",
        name: "Lock In Your Mortgage Rate",
        description: "Secure today's rate on your pre-approved mortgage before it changes.",
        cta: "Lock in my rate",
        mobileName: "Lock In Your Rate",
        mobileDescription: "Secure today's rate before it changes.",
        mobileCta: "Lock in",
        requiredSignals: ["mortgage_calc"],
        priority: 75,
        affinityTags: ["mortgage_calc"],
        imageUrl: "/banners/mortgage-loans.png",
        mobileImageUrl: "/banners/mortgage-loans-mobile.png",
      },
      {
        id: "finish_application",
        name: "Finish Your Application — Fee Waived",
        description: "Complete your mortgage application now and we'll waive the processing fee.",
        cta: "Finish my application",
        mobileName: "Finish & Skip the Fee",
        mobileDescription: "Finish now, fee waived.",
        mobileCta: "Finish now",
        requiredSignals: ["app_abandoned"],
        priority: 90,
        affinityTags: ["app_abandoned"],
        imageUrl: "/banners/mortgage-loans.png",
        mobileImageUrl: "/banners/mortgage-loans-mobile.png",
      },
      {
        id: "loyalty_reward",
        name: "A Thank-You, On Us: 6 Months Fee-Free",
        description: "After your recent call, we've waived your account fees for the next 6 months — already applied.",
        cta: "Claim my reward",
        mobileName: "6 Months, Fee-Free",
        mobileDescription: "Fees waived for 6 months. Already applied.",
        mobileCta: "Claim reward",
        requiredSignals: ["sentiment_dissatisfied", "customer_existing"],
        priority: 95,
        affinityTags: ["sentiment_dissatisfied"],
        imageUrl: "/banners/private-banking.png",
        mobileImageUrl: "/banners/private-banking-mobile.png",
      },
      {
        id: "family_protection",
        name: "Protect What Matters: Family Coverage Review",
        description: "Now that your family is growing, let's make sure your coverage keeps up.",
        cta: "Review my coverage",
        mobileName: "Protect Your Family",
        mobileDescription: "Make sure your coverage keeps up.",
        mobileCta: "Review coverage",
        requiredSignals: ["has_family"],
        priority: 80,
        affinityTags: ["has_family", "profession_stay_home"],
        imageUrl: "/banners/family-protection.png",
        mobileImageUrl: "/banners/family-protection-mobile.png",
      },
      {
        id: "business_banking",
        name: "Business Banking for the Self-Employed",
        description: "Flexible business banking built for variable, self-employed income.",
        cta: "Open a business account",
        mobileName: "Banking for the Self-Employed",
        mobileDescription: "Built for variable, self-employed income.",
        mobileCta: "Open account",
        requiredSignals: ["profession_hairdresser"],
        priority: 62,
        affinityTags: ["profession_hairdresser"],
        imageUrl: "/banners/self-employed-banking.png",
        mobileImageUrl: "/banners/self-employed-banking-mobile.png",
      },
      {
        id: "premium_digital",
        name: "Open a Premium Digital Account in Minutes",
        description: "Built for busy professionals — everything set up from your phone, no branch visit needed.",
        cta: "Open my account",
        mobileName: "Open an Account in Minutes",
        mobileDescription: "Set up from your phone. No branch visit.",
        mobileCta: "Open account",
        requiredSignals: ["profession_pm", "customer_prospect"],
        priority: 62,
        affinityTags: ["profession_pm"],
        imageUrl: "/banners/premium-digital.png",
        mobileImageUrl: "/banners/premium-digital-mobile.png",
      },
      {
        id: "later_life_planning",
        name: "Plan for What's Next",
        description: "Later-life banking and estate planning, made simple.",
        cta: "Start planning",
        mobileDescription: "Estate planning, made simple.",
        requiredSignals: ["age_50s"],
        priority: 65,
        affinityTags: ["age_50s"],
        imageUrl: "/banners/retirement.png",
        mobileImageUrl: "/banners/retirement-mobile.png",
      },
      {
        id: "starter_banking",
        name: "Starter Banking Bundle",
        description: "Everything you need to build good financial habits early.",
        cta: "Get started",
        mobileDescription: "Build good habits early.",
        requiredSignals: ["age_30s"],
        priority: 60,
        affinityTags: ["age_30s"],
        imageUrl: "/banners/savings-accounts.png",
        mobileImageUrl: "/banners/savings-accounts-mobile.png",
      },
      {
        id: "welcome_savings",
        name: "Welcome Bonus: Open a Savings Account",
        description: "A general-interest pick for customers still exploring their options.",
        cta: "Open a savings account",
        mobileName: "Welcome Bonus: Open Savings",
        mobileDescription: "Still exploring your options? Start here.",
        mobileCta: "Open savings",
        requiredSignals: [],
        priority: 40,
        affinityTags: [],
        imageUrl: "/banners/savings-accounts.png",
        mobileImageUrl: "/banners/savings-accounts-mobile.png",
      },
    ],
  },
  lukas: {
    collectionName: "SecurFinancial Wealth & Retirement Offers",
    offers: [
      {
        id: "boost_retirement",
        name: "Boost Your Retirement Contributions",
        description: "Increase your contribution rate and see the long-term projected impact.",
        cta: "Boost my contributions",
        mobileName: "Boost Your Retirement",
        mobileDescription: "See the long-term impact.",
        mobileCta: "Boost now",
        requiredSignals: ["retirement_interest"],
        priority: 70,
        affinityTags: ["retirement_interest", "age_50s", "profession_pm"],
        imageUrl: "/banners/retirement.png",
        mobileImageUrl: "/banners/retirement-mobile.png",
      },
      {
        id: "finish_investment_setup",
        name: "Complete Your Investment Setup",
        description: "You're almost there — finish setting up your investment account today.",
        cta: "Finish my setup",
        mobileName: "Finish Your Setup",
        mobileDescription: "Almost there — finish today.",
        requiredSignals: ["app_abandoned"],
        priority: 88,
        affinityTags: ["app_abandoned"],
        imageUrl: "/banners/investment.png",
        mobileImageUrl: "/banners/investment-mobile.png",
      },
      {
        id: "loyalty_reward",
        name: "A Thank-You, On Us: Reduced Advisory Fees",
        description: "After your recent call, we've reduced your advisory fees for the next quarter — already applied.",
        cta: "Claim my reward",
        mobileName: "Reduced Advisory Fees",
        mobileDescription: "Fees reduced this quarter. Already applied.",
        mobileCta: "Claim reward",
        requiredSignals: ["sentiment_dissatisfied", "customer_existing"],
        priority: 95,
        affinityTags: ["sentiment_dissatisfied"],
        imageUrl: "/banners/private-banking.png",
        mobileImageUrl: "/banners/private-banking-mobile.png",
      },
      {
        id: "family_protection",
        name: "Set Up a Trust for Your Family",
        description: "Now that your family is growing, plan how your wealth protects them too.",
        cta: "Start my trust",
        mobileName: "Set Up a Family Trust",
        mobileDescription: "Plan how your wealth protects them.",
        mobileCta: "Start trust",
        requiredSignals: ["has_family"],
        priority: 80,
        affinityTags: ["has_family", "profession_stay_home"],
        imageUrl: "/banners/family-protection.png",
        mobileImageUrl: "/banners/family-protection-mobile.png",
      },
      {
        id: "business_banking",
        name: "Business Banking for the Self-Employed",
        description: "Flexible business banking built for variable, self-employed income.",
        cta: "Open a business account",
        mobileName: "Banking for the Self-Employed",
        mobileDescription: "Built for variable, self-employed income.",
        mobileCta: "Open account",
        requiredSignals: ["profession_hairdresser"],
        priority: 62,
        affinityTags: ["profession_hairdresser"],
        imageUrl: "/banners/self-employed-banking.png",
        mobileImageUrl: "/banners/self-employed-banking-mobile.png",
      },
      {
        id: "premium_digital",
        name: "Open a Premium Digital Account in Minutes",
        description: "Built for busy professionals — everything set up from your phone, no branch visit needed.",
        cta: "Open my account",
        mobileName: "Open an Account in Minutes",
        mobileDescription: "Set up from your phone. No branch visit.",
        mobileCta: "Open account",
        requiredSignals: ["profession_pm", "customer_prospect"],
        priority: 62,
        affinityTags: ["profession_pm"],
        imageUrl: "/banners/premium-digital.png",
        mobileImageUrl: "/banners/premium-digital-mobile.png",
      },
      {
        id: "early_investing",
        name: "Start Investing Early",
        description: "Small contributions now add up significantly by retirement.",
        cta: "Start investing",
        mobileDescription: "Small amounts add up by retirement.",
        requiredSignals: ["age_30s"],
        priority: 60,
        affinityTags: ["audience_emerging_investors"],
        imageUrl: "/banners/investment.png",
        mobileImageUrl: "/banners/investment-mobile.png",
      },
      {
        id: "savings_calculator",
        name: "Explore Our Savings Calculator",
        description: "A general-interest pick for customers still exploring their options.",
        cta: "Try the calculator",
        mobileName: "Try Our Savings Calculator",
        mobileDescription: "Still exploring? Start here.",
        requiredSignals: [],
        priority: 35,
        affinityTags: [],
        imageUrl: "/banners/savings-accounts.png",
        mobileImageUrl: "/banners/savings-accounts-mobile.png",
      },
    ],
  },
  marcus: {
    collectionName: "TrailGear Outdoor Retail Offers",
    offers: [
      {
        id: "shoe_flash_sale",
        name: "Running Shoe Flash Sale",
        description: "The shoes you've been eyeing, now 15% off for 48 hours.",
        cta: "Shop the sale",
        mobileDescription: "15% off for 48 hours.",
        requiredSignals: ["shoes_interest"],
        priority: 65,
        affinityTags: ["shoes_interest", "age_30s"],
      },
      {
        id: "finish_order",
        name: "Finish Your Order — Free Shipping",
        description: "Complete your cart today and shipping is on us.",
        cta: "Finish my order",
        mobileName: "Finish Order, Free Shipping",
        mobileDescription: "Shipping's on us today.",
        requiredSignals: ["cart_abandoned"],
        priority: 85,
        affinityTags: ["cart_abandoned"],
      },
      {
        id: "recovery_discount",
        name: "We're Sorry — Here's 20% Off Your Next Order",
        description: "We want to make up for what went wrong on your last order.",
        cta: "Claim my discount",
        mobileName: "Sorry! 20% Off Next Order",
        mobileDescription: "Making up for what went wrong.",
        mobileCta: "Claim discount",
        requiredSignals: ["sentiment_dissatisfied"],
        priority: 95,
        affinityTags: ["sentiment_dissatisfied"],
      },
      {
        id: "rain_jackets",
        name: "Weatherproof Jacket Picks",
        description: "Curated rain gear picked for your local climate.",
        cta: "Shop rain gear",
        mobileDescription: "Rain gear for your climate.",
        requiredSignals: ["rainy_climate"],
        priority: 55,
        affinityTags: ["rainy_climate", "age_50s"],
      },
      {
        id: "new_arrivals",
        name: "New Arrivals This Week",
        description: "A general-interest pick for browsing customers.",
        cta: "See what's new",
        mobileDescription: "Fresh picks for browsing.",
        requiredSignals: [],
        priority: 35,
        affinityTags: [],
      },
    ],
  },
};
