import { LocalizedText } from "./localized";
import { Offer } from "./types";

export const offersByPersona: Record<string, { collectionName: LocalizedText; offers: Offer[] }> = {
  anna: {
    collectionName: {
      en: "SecurFinancial Mortgage & Banking Offers",
      pl: "Oferty hipoteczne i bankowe SecurFinancial",
      de: "SecurFinancial Hypotheken- und Bankangebote",
    },
    offers: [
      {
        id: "lock_mortgage_rate",
        name: {
          en: "Lock In Your Mortgage Rate",
          pl: "Zablokuj swoje oprocentowanie kredytu hipotecznego",
          de: "Sichern Sie sich Ihren Hypothekenzins",
        },
        description: {
          en: "Secure today's rate on your pre-approved mortgage before it changes.",
          pl: "Zabezpiecz dzisiejsze oprocentowanie wstępnie zatwierdzonego kredytu hipotecznego, zanim się zmieni.",
          de: "Sichern Sie sich den heutigen Zinssatz für Ihre vorab genehmigte Hypothek, bevor er sich ändert.",
        },
        cta: { en: "Lock in my rate", pl: "Zablokuj moje oprocentowanie", de: "Zinssatz sichern" },
        mobileName: {
          en: "Lock In Your Rate",
          pl: "Zablokuj oprocentowanie",
          de: "Zinssatz sichern",
        },
        mobileDescription: {
          en: "Secure today's rate before it changes.",
          pl: "Zabezpiecz dzisiejsze oprocentowanie, zanim się zmieni.",
          de: "Sichern Sie sich den heutigen Zinssatz, bevor er sich ändert.",
        },
        mobileCta: { en: "Lock in", pl: "Zablokuj", de: "Sichern" },
        requiredSignals: ["mortgage_calc"],
        priority: 75,
        affinityTags: ["mortgage_calc"],
        imageUrl: "/banners/mortgage-loans.png",
        mobileImageUrl: "/banners/mortgage-loans-mobile.png",
      },
      {
        id: "finish_application",
        name: {
          en: "Finish Your Application — Fee Waived",
          pl: "Dokończ wniosek — bez opłaty",
          de: "Antrag abschließen — Gebühr erlassen",
        },
        description: {
          en: "Complete your mortgage application now and we'll waive the processing fee.",
          pl: "Dokończ teraz swój wniosek o kredyt hipoteczny, a zniesiemy opłatę za jego przetworzenie.",
          de: "Schließen Sie jetzt Ihren Hypothekenantrag ab, und wir erlassen Ihnen die Bearbeitungsgebühr.",
        },
        cta: { en: "Finish my application", pl: "Dokończ mój wniosek", de: "Antrag abschließen" },
        mobileName: {
          en: "Finish & Skip the Fee",
          pl: "Dokończ i pomiń opłatę",
          de: "Abschließen & Gebühr sparen",
        },
        mobileDescription: {
          en: "Finish now, fee waived.",
          pl: "Dokończ teraz, bez opłaty.",
          de: "Jetzt abschließen, Gebühr erlassen.",
        },
        mobileCta: { en: "Finish now", pl: "Dokończ teraz", de: "Jetzt abschließen" },
        requiredSignals: ["app_abandoned"],
        priority: 90,
        affinityTags: ["app_abandoned"],
        imageUrl: "/banners/mortgage-loans.png",
        mobileImageUrl: "/banners/mortgage-loans-mobile.png",
      },
      {
        id: "loyalty_reward",
        name: {
          en: "A Thank-You, On Us: 6 Months Fee-Free",
          pl: "Podziękowanie od nas: 6 miesięcy bez opłat",
          de: "Ein Dankeschön von uns: 6 Monate gebührenfrei",
        },
        description: {
          en: "After your recent call, we've waived your account fees for the next 6 months — already applied.",
          pl: "Po Twoim niedawnym telefonie zniosliśmy opłaty za konto na kolejne 6 miesięcy — zmiana już obowiązuje.",
          de: "Nach Ihrem kürzlichen Anruf haben wir Ihre Kontogebühren für die nächsten 6 Monate erlassen — bereits angewendet.",
        },
        cta: { en: "Claim my reward", pl: "Odbierz nagrodę", de: "Prämie einlösen" },
        mobileName: { en: "6 Months, Fee-Free", pl: "6 miesięcy bez opłat", de: "6 Monate gebührenfrei" },
        mobileDescription: {
          en: "Fees waived for 6 months. Already applied.",
          pl: "Opłaty zniesione na 6 miesięcy. Zmiana już obowiązuje.",
          de: "Gebühren für 6 Monate erlassen. Bereits angewendet.",
        },
        mobileCta: { en: "Claim reward", pl: "Odbierz nagrodę", de: "Prämie einlösen" },
        requiredSignals: ["sentiment_dissatisfied", "customer_existing"],
        priority: 95,
        affinityTags: ["sentiment_dissatisfied"],
        imageUrl: "/banners/private-banking.png",
        mobileImageUrl: "/banners/private-banking-mobile.png",
      },
      {
        id: "family_protection",
        name: {
          en: "Protect What Matters: Family Coverage Review",
          pl: "Chroń to, co ważne: przegląd ochrony rodzinnej",
          de: "Schützen Sie, was zählt: Familienschutz-Check",
        },
        description: {
          en: "Now that your family is growing, let's make sure your coverage keeps up.",
          pl: "Twoja rodzina się powiększa — upewnijmy się, że Twoja ochrona nadąża za zmianami.",
          de: "Da Ihre Familie wächst, sollten wir sicherstellen, dass Ihr Versicherungsschutz mithält.",
        },
        cta: { en: "Review my coverage", pl: "Sprawdź moją ochronę", de: "Schutz überprüfen" },
        mobileName: { en: "Protect Your Family", pl: "Chroń swoją rodzinę", de: "Familie schützen" },
        mobileDescription: {
          en: "Make sure your coverage keeps up.",
          pl: "Upewnij się, że Twoja ochrona nadąża za zmianami.",
          de: "Stellen Sie sicher, dass Ihr Schutz mithält.",
        },
        mobileCta: { en: "Review coverage", pl: "Sprawdź ochronę", de: "Schutz prüfen" },
        requiredSignals: ["has_family"],
        priority: 80,
        affinityTags: ["has_family", "profession_stay_home"],
        imageUrl: "/banners/family-protection.png",
        mobileImageUrl: "/banners/family-protection-mobile.png",
      },
      {
        id: "business_banking",
        name: {
          en: "Business Banking for the Self-Employed",
          pl: "Bankowość biznesowa dla samozatrudnionych",
          de: "Geschäftskonten für Selbstständige",
        },
        description: {
          en: "Flexible business banking built for variable, self-employed income.",
          pl: "Elastyczna bankowość biznesowa stworzona dla zmiennych dochodów z samozatrudnienia.",
          de: "Flexible Geschäftskonten, konzipiert für variable Einkünfte von Selbstständigen.",
        },
        cta: { en: "Open a business account", pl: "Otwórz konto firmowe", de: "Geschäftskonto eröffnen" },
        mobileName: {
          en: "Banking for the Self-Employed",
          pl: "Bankowość dla samozatrudnionych",
          de: "Banking für Selbstständige",
        },
        mobileDescription: {
          en: "Built for variable, self-employed income.",
          pl: "Stworzone dla zmiennych dochodów z samozatrudnienia.",
          de: "Konzipiert für variable Einkünfte von Selbstständigen.",
        },
        mobileCta: { en: "Open account", pl: "Otwórz konto", de: "Konto eröffnen" },
        requiredSignals: ["profession_hairdresser"],
        priority: 62,
        affinityTags: ["profession_hairdresser"],
        imageUrl: "/banners/self-employed-banking.png",
        mobileImageUrl: "/banners/self-employed-banking-mobile.png",
      },
      {
        id: "premium_digital",
        name: {
          en: "Open a Premium Digital Account in Minutes",
          pl: "Otwórz konto Premium Digital w kilka minut",
          de: "Premium-Digitalkonto in wenigen Minuten eröffnen",
        },
        description: {
          en: "Built for busy professionals — everything set up from your phone, no branch visit needed.",
          pl: "Stworzone dla zapracowanych profesjonalistów — wszystko ustawisz z telefonu, bez wizyty w oddziale.",
          de: "Für vielbeschäftigte Berufstätige — alles vom Smartphone aus einrichten, ohne Filialbesuch.",
        },
        cta: { en: "Open my account", pl: "Otwórz moje konto", de: "Konto eröffnen" },
        mobileName: {
          en: "Open an Account in Minutes",
          pl: "Otwórz konto w kilka minut",
          de: "Konto in wenigen Minuten eröffnen",
        },
        mobileDescription: {
          en: "Set up from your phone. No branch visit.",
          pl: "Ustaw z telefonu. Bez wizyty w oddziale.",
          de: "Einrichtung per Smartphone. Kein Filialbesuch.",
        },
        mobileCta: { en: "Open account", pl: "Otwórz konto", de: "Konto eröffnen" },
        requiredSignals: ["profession_pm", "customer_prospect"],
        priority: 62,
        affinityTags: ["profession_pm"],
        imageUrl: "/banners/premium-digital.png",
        mobileImageUrl: "/banners/premium-digital-mobile.png",
      },
      {
        id: "later_life_planning",
        name: { en: "Plan for What's Next", pl: "Zaplanuj to, co przed Tobą", de: "Planen Sie, was als Nächstes kommt" },
        description: {
          en: "Later-life banking and estate planning, made simple.",
          pl: "Bankowość na później i planowanie spadkowe — w prostej formie.",
          de: "Banking im Ruhestand und Nachlassplanung, einfach gemacht.",
        },
        cta: { en: "Start planning", pl: "Zacznij planować", de: "Planung starten" },
        mobileDescription: {
          en: "Estate planning, made simple.",
          pl: "Planowanie spadkowe w prostej formie.",
          de: "Nachlassplanung, einfach gemacht.",
        },
        requiredSignals: ["age_50s"],
        priority: 65,
        affinityTags: ["age_50s"],
        imageUrl: "/banners/retirement.png",
        mobileImageUrl: "/banners/retirement-mobile.png",
      },
      {
        id: "starter_banking",
        name: { en: "Starter Banking Bundle", pl: "Pakiet bankowy dla początkujących", de: "Starter-Bankpaket" },
        description: {
          en: "Everything you need to build good financial habits early.",
          pl: "Wszystko, czego potrzebujesz, by wcześnie wyrobić sobie dobre nawyki finansowe.",
          de: "Alles, was Sie brauchen, um früh gute Finanzgewohnheiten aufzubauen.",
        },
        cta: { en: "Get started", pl: "Zacznij teraz", de: "Jetzt starten" },
        mobileDescription: {
          en: "Build good habits early.",
          pl: "Wyrób sobie dobre nawyki wcześnie.",
          de: "Bauen Sie früh gute Gewohnheiten auf.",
        },
        requiredSignals: ["age_30s"],
        priority: 60,
        affinityTags: ["age_30s"],
        imageUrl: "/banners/savings-accounts.png",
        mobileImageUrl: "/banners/savings-accounts-mobile.png",
      },
      {
        id: "welcome_savings",
        name: {
          en: "Welcome Bonus: Open a Savings Account",
          pl: "Bonus powitalny: otwórz konto oszczędnościowe",
          de: "Willkommensbonus: Sparkonto eröffnen",
        },
        description: {
          en: "A general-interest pick for customers still exploring their options.",
          pl: "Propozycja ogólna dla klientów, którzy wciąż rozważają swoje opcje.",
          de: "Ein allgemeiner Vorschlag für Kunden, die noch ihre Möglichkeiten prüfen.",
        },
        cta: { en: "Open a savings account", pl: "Otwórz konto oszczędnościowe", de: "Sparkonto eröffnen" },
        mobileName: {
          en: "Welcome Bonus: Open Savings",
          pl: "Bonus powitalny: konto oszczędnościowe",
          de: "Willkommensbonus: Sparkonto",
        },
        mobileDescription: {
          en: "Still exploring your options? Start here.",
          pl: "Wciąż rozważasz opcje? Zacznij tutaj.",
          de: "Noch unentschlossen? Hier starten.",
        },
        mobileCta: { en: "Open savings", pl: "Otwórz konto", de: "Sparkonto eröffnen" },
        requiredSignals: [],
        priority: 40,
        affinityTags: [],
        imageUrl: "/banners/savings-accounts.png",
        mobileImageUrl: "/banners/savings-accounts-mobile.png",
      },
    ],
  },
  lukas: {
    collectionName: {
      en: "SecurFinancial Wealth & Retirement Offers",
      pl: "Oferty majątkowe i emerytalne SecurFinancial",
      de: "SecurFinancial Vermögens- und Altersvorsorgeangebote",
    },
    offers: [
      {
        id: "boost_retirement",
        name: {
          en: "Boost Your Retirement Contributions",
          pl: "Zwiększ swoje składki emerytalne",
          de: "Erhöhen Sie Ihre Altersvorsorgebeiträge",
        },
        description: {
          en: "Increase your contribution rate and see the long-term projected impact.",
          pl: "Zwiększ stawkę składki i zobacz długoterminowy prognozowany efekt.",
          de: "Erhöhen Sie Ihre Beitragsrate und sehen Sie die langfristige prognostizierte Wirkung.",
        },
        cta: { en: "Boost my contributions", pl: "Zwiększ moje składki", de: "Beiträge erhöhen" },
        mobileName: {
          en: "Boost Your Retirement",
          pl: "Zwiększ swoją emeryturę",
          de: "Altersvorsorge steigern",
        },
        mobileDescription: {
          en: "See the long-term impact.",
          pl: "Zobacz długoterminowy efekt.",
          de: "Sehen Sie die langfristige Wirkung.",
        },
        mobileCta: { en: "Boost now", pl: "Zwiększ teraz", de: "Jetzt erhöhen" },
        requiredSignals: ["retirement_interest"],
        priority: 70,
        affinityTags: ["retirement_interest", "age_50s", "profession_pm"],
        imageUrl: "/banners/retirement.png",
        mobileImageUrl: "/banners/retirement-mobile.png",
      },
      {
        id: "finish_investment_setup",
        name: {
          en: "Complete Your Investment Setup",
          pl: "Dokończ konfigurację inwestycji",
          de: "Schließen Sie Ihre Investment-Einrichtung ab",
        },
        description: {
          en: "You're almost there — finish setting up your investment account today.",
          pl: "Jesteś już prawie na miejscu — dokończ dziś konfigurację rachunku inwestycyjnego.",
          de: "Sie sind fast am Ziel — schließen Sie heute die Einrichtung Ihres Investmentkontos ab.",
        },
        cta: { en: "Finish my setup", pl: "Dokończ konfigurację", de: "Einrichtung abschließen" },
        mobileName: { en: "Finish Your Setup", pl: "Dokończ konfigurację", de: "Einrichtung abschließen" },
        mobileDescription: {
          en: "Almost there — finish today.",
          pl: "Już prawie gotowe — dokończ dziś.",
          de: "Fast geschafft — heute abschließen.",
        },
        requiredSignals: ["app_abandoned"],
        priority: 88,
        affinityTags: ["app_abandoned"],
        imageUrl: "/banners/investment.png",
        mobileImageUrl: "/banners/investment-mobile.png",
      },
      {
        id: "loyalty_reward",
        name: {
          en: "A Thank-You, On Us: Reduced Advisory Fees",
          pl: "Podziękowanie od nas: obniżone opłaty doradcze",
          de: "Ein Dankeschön von uns: reduzierte Beratungsgebühren",
        },
        description: {
          en: "After your recent call, we've reduced your advisory fees for the next quarter — already applied.",
          pl: "Po Twoim niedawnym telefonie obniżyliśmy opłaty doradcze na kolejny kwartał — zmiana już obowiązuje.",
          de: "Nach Ihrem kürzlichen Anruf haben wir Ihre Beratungsgebühren für das nächste Quartal reduziert — bereits angewendet.",
        },
        cta: { en: "Claim my reward", pl: "Odbierz nagrodę", de: "Prämie einlösen" },
        mobileName: {
          en: "Reduced Advisory Fees",
          pl: "Obniżone opłaty doradcze",
          de: "Reduzierte Beratungsgebühren",
        },
        mobileDescription: {
          en: "Fees reduced this quarter. Already applied.",
          pl: "Opłaty obniżone w tym kwartale. Zmiana już obowiązuje.",
          de: "Gebühren in diesem Quartal reduziert. Bereits angewendet.",
        },
        mobileCta: { en: "Claim reward", pl: "Odbierz nagrodę", de: "Prämie einlösen" },
        requiredSignals: ["sentiment_dissatisfied", "customer_existing"],
        priority: 95,
        affinityTags: ["sentiment_dissatisfied"],
        imageUrl: "/banners/private-banking.png",
        mobileImageUrl: "/banners/private-banking-mobile.png",
      },
      {
        id: "family_protection",
        name: {
          en: "Set Up a Trust for Your Family",
          pl: "Załóż fundusz powierniczy dla rodziny",
          de: "Richten Sie einen Treuhandfonds für Ihre Familie ein",
        },
        description: {
          en: "Now that your family is growing, plan how your wealth protects them too.",
          pl: "Twoja rodzina się powiększa — zaplanuj, jak Twój majątek będzie ją chronił.",
          de: "Da Ihre Familie wächst, planen Sie, wie Ihr Vermögen sie ebenfalls schützt.",
        },
        cta: { en: "Start my trust", pl: "Załóż fundusz", de: "Treuhandfonds einrichten" },
        mobileName: { en: "Set Up a Family Trust", pl: "Załóż fundusz rodzinny", de: "Familientreuhand einrichten" },
        mobileDescription: {
          en: "Plan how your wealth protects them.",
          pl: "Zaplanuj, jak Twój majątek będzie ich chronił.",
          de: "Planen Sie, wie Ihr Vermögen sie schützt.",
        },
        mobileCta: { en: "Start trust", pl: "Załóż fundusz", de: "Fonds einrichten" },
        requiredSignals: ["has_family"],
        priority: 80,
        affinityTags: ["has_family", "profession_stay_home"],
        imageUrl: "/banners/family-protection.png",
        mobileImageUrl: "/banners/family-protection-mobile.png",
      },
      {
        id: "business_banking",
        name: {
          en: "Business Banking for the Self-Employed",
          pl: "Bankowość biznesowa dla samozatrudnionych",
          de: "Geschäftskonten für Selbstständige",
        },
        description: {
          en: "Flexible business banking built for variable, self-employed income.",
          pl: "Elastyczna bankowość biznesowa stworzona dla zmiennych dochodów z samozatrudnienia.",
          de: "Flexible Geschäftskonten, konzipiert für variable Einkünfte von Selbstständigen.",
        },
        cta: { en: "Open a business account", pl: "Otwórz konto firmowe", de: "Geschäftskonto eröffnen" },
        mobileName: {
          en: "Banking for the Self-Employed",
          pl: "Bankowość dla samozatrudnionych",
          de: "Banking für Selbstständige",
        },
        mobileDescription: {
          en: "Built for variable, self-employed income.",
          pl: "Stworzone dla zmiennych dochodów z samozatrudnienia.",
          de: "Konzipiert für variable Einkünfte von Selbstständigen.",
        },
        mobileCta: { en: "Open account", pl: "Otwórz konto", de: "Konto eröffnen" },
        requiredSignals: ["profession_hairdresser"],
        priority: 62,
        affinityTags: ["profession_hairdresser"],
        imageUrl: "/banners/self-employed-banking.png",
        mobileImageUrl: "/banners/self-employed-banking-mobile.png",
      },
      {
        id: "premium_digital",
        name: {
          en: "Open a Premium Digital Account in Minutes",
          pl: "Otwórz konto Premium Digital w kilka minut",
          de: "Premium-Digitalkonto in wenigen Minuten eröffnen",
        },
        description: {
          en: "Built for busy professionals — everything set up from your phone, no branch visit needed.",
          pl: "Stworzone dla zapracowanych profesjonalistów — wszystko ustawisz z telefonu, bez wizyty w oddziale.",
          de: "Für vielbeschäftigte Berufstätige — alles vom Smartphone aus einrichten, ohne Filialbesuch.",
        },
        cta: { en: "Open my account", pl: "Otwórz moje konto", de: "Konto eröffnen" },
        mobileName: {
          en: "Open an Account in Minutes",
          pl: "Otwórz konto w kilka minut",
          de: "Konto in wenigen Minuten eröffnen",
        },
        mobileDescription: {
          en: "Set up from your phone. No branch visit.",
          pl: "Ustaw z telefonu. Bez wizyty w oddziale.",
          de: "Einrichtung per Smartphone. Kein Filialbesuch.",
        },
        mobileCta: { en: "Open account", pl: "Otwórz konto", de: "Konto eröffnen" },
        requiredSignals: ["profession_pm", "customer_prospect"],
        priority: 62,
        affinityTags: ["profession_pm"],
        imageUrl: "/banners/premium-digital.png",
        mobileImageUrl: "/banners/premium-digital-mobile.png",
      },
      {
        id: "early_investing",
        name: { en: "Start Investing Early", pl: "Zacznij inwestować wcześnie", de: "Früh mit dem Investieren beginnen" },
        description: {
          en: "Small contributions now add up significantly by retirement.",
          pl: "Niewielkie wpłaty teraz znacząco się sumują do czasu emerytury.",
          de: "Kleine Beiträge summieren sich bis zur Rente erheblich.",
        },
        cta: { en: "Start investing", pl: "Zacznij inwestować", de: "Investieren beginnen" },
        mobileDescription: {
          en: "Small amounts add up by retirement.",
          pl: "Małe kwoty sumują się do czasu emerytury.",
          de: "Kleine Beträge summieren sich bis zur Rente.",
        },
        requiredSignals: ["age_30s"],
        priority: 60,
        affinityTags: ["audience_emerging_investors"],
        imageUrl: "/banners/investment.png",
        mobileImageUrl: "/banners/investment-mobile.png",
      },
      {
        id: "savings_calculator",
        name: {
          en: "Explore Our Savings Calculator",
          pl: "Sprawdź nasz kalkulator oszczędności",
          de: "Entdecken Sie unseren Sparrechner",
        },
        description: {
          en: "A general-interest pick for customers still exploring their options.",
          pl: "Propozycja ogólna dla klientów, którzy wciąż rozważają swoje opcje.",
          de: "Ein allgemeiner Vorschlag für Kunden, die noch ihre Möglichkeiten prüfen.",
        },
        cta: { en: "Try the calculator", pl: "Wypróbuj kalkulator", de: "Rechner ausprobieren" },
        mobileName: {
          en: "Try Our Savings Calculator",
          pl: "Wypróbuj kalkulator oszczędności",
          de: "Sparrechner ausprobieren",
        },
        mobileDescription: {
          en: "Still exploring? Start here.",
          pl: "Wciąż rozważasz opcje? Zacznij tutaj.",
          de: "Noch unentschlossen? Hier starten.",
        },
        requiredSignals: [],
        priority: 35,
        affinityTags: [],
        imageUrl: "/banners/savings-accounts.png",
        mobileImageUrl: "/banners/savings-accounts-mobile.png",
      },
    ],
  },
  marcus: {
    collectionName: {
      en: "TrailGear Outdoor Retail Offers",
      pl: "Oferty outdoorowe TrailGear",
      de: "TrailGear Outdoor-Angebote",
    },
    offers: [
      {
        id: "shoe_flash_sale",
        name: { en: "Running Shoe Flash Sale", pl: "Błyskawiczna wyprzedaż butów do biegania", de: "Blitzverkauf Laufschuhe" },
        description: {
          en: "The shoes you've been eyeing, now 15% off for 48 hours.",
          pl: "Buty, na które od dawna patrzysz, teraz 15% taniej przez 48 godzin.",
          de: "Die Schuhe, die Sie im Blick hatten, jetzt 48 Stunden lang 15 % günstiger.",
        },
        cta: { en: "Shop the sale", pl: "Zobacz wyprzedaż", de: "Zum Angebot" },
        mobileDescription: {
          en: "15% off for 48 hours.",
          pl: "15% taniej przez 48 godzin.",
          de: "48 Stunden lang 15 % günstiger.",
        },
        requiredSignals: ["shoes_interest"],
        priority: 65,
        affinityTags: ["shoes_interest", "age_30s"],
      },
      {
        id: "finish_order",
        name: {
          en: "Finish Your Order — Free Shipping",
          pl: "Dokończ zamówienie — darmowa dostawa",
          de: "Bestellung abschließen — kostenloser Versand",
        },
        description: {
          en: "Complete your cart today and shipping is on us.",
          pl: "Dokończ dziś swój koszyk, a dostawę bierzemy na siebie.",
          de: "Schließen Sie Ihren Warenkorb heute ab, der Versand geht auf uns.",
        },
        cta: { en: "Finish my order", pl: "Dokończ zamówienie", de: "Bestellung abschließen" },
        mobileName: { en: "Finish Order, Free Shipping", pl: "Dokończ, darmowa dostawa", de: "Abschließen, gratis Versand" },
        mobileDescription: {
          en: "Shipping's on us today.",
          pl: "Dziś dostawa na nas.",
          de: "Heute geht der Versand auf uns.",
        },
        requiredSignals: ["cart_abandoned"],
        priority: 85,
        affinityTags: ["cart_abandoned"],
      },
      {
        id: "recovery_discount",
        name: {
          en: "We're Sorry — Here's 20% Off Your Next Order",
          pl: "Przepraszamy — 20% zniżki na kolejne zamówienie",
          de: "Es tut uns leid — 20 % Rabatt auf Ihre nächste Bestellung",
        },
        description: {
          en: "We want to make up for what went wrong on your last order.",
          pl: "Chcemy zrekompensować to, co poszło nie tak przy Twoim ostatnim zamówieniu.",
          de: "Wir möchten wiedergutmachen, was bei Ihrer letzten Bestellung schiefgelaufen ist.",
        },
        cta: { en: "Claim my discount", pl: "Odbierz zniżkę", de: "Rabatt einlösen" },
        mobileName: {
          en: "Sorry! 20% Off Next Order",
          pl: "Przepraszamy! 20% zniżki",
          de: "Entschuldigung! 20 % Rabatt",
        },
        mobileDescription: {
          en: "Making up for what went wrong.",
          pl: "Rekompensata za to, co poszło nie tak.",
          de: "Wiedergutmachung für das Missgeschick.",
        },
        mobileCta: { en: "Claim discount", pl: "Odbierz zniżkę", de: "Rabatt einlösen" },
        requiredSignals: ["sentiment_dissatisfied"],
        priority: 95,
        affinityTags: ["sentiment_dissatisfied"],
      },
      {
        id: "rain_jackets",
        name: { en: "Weatherproof Jacket Picks", pl: "Wybór kurtek nieprzemakalnych", de: "Auswahl wetterfester Jacken" },
        description: {
          en: "Curated rain gear picked for your local climate.",
          pl: "Wyselekcjonowany sprzęt przeciwdeszczowy dopasowany do Twojego klimatu.",
          de: "Ausgewählte Regenbekleidung, passend zu Ihrem regionalen Klima.",
        },
        cta: { en: "Shop rain gear", pl: "Zobacz sprzęt przeciwdeszczowy", de: "Zur Regenausrüstung" },
        mobileDescription: {
          en: "Rain gear for your climate.",
          pl: "Sprzęt przeciwdeszczowy dla Twojego klimatu.",
          de: "Regenausrüstung für Ihr Klima.",
        },
        requiredSignals: ["rainy_climate"],
        priority: 55,
        affinityTags: ["rainy_climate", "age_50s"],
      },
      {
        id: "new_arrivals",
        name: { en: "New Arrivals This Week", pl: "Nowości w tym tygodniu", de: "Neuheiten diese Woche" },
        description: {
          en: "A general-interest pick for browsing customers.",
          pl: "Propozycja ogólna dla klientów przeglądających ofertę.",
          de: "Ein allgemeiner Vorschlag für stöbernde Kunden.",
        },
        cta: { en: "See what's new", pl: "Zobacz nowości", de: "Neuheiten ansehen" },
        mobileDescription: {
          en: "Fresh picks for browsing.",
          pl: "Świeże propozycje do przeglądania.",
          de: "Frische Vorschläge zum Stöbern.",
        },
        requiredSignals: [],
        priority: 35,
        affinityTags: [],
      },
    ],
  },
};
